[versions]
agp = "8.13.2"
kotlin = "2.2.0"
coreKtx = "1.16.0"
appcompat = "1.7.1"
composeBom = "2025.07.00"
tvFoundation = "1.0.0-alpha12"
tvMaterial = "1.0.1"
lifecycleRuntimeKtx = "2.9.2"
activityCompose = "1.10.1"
hilt = "2.57"
hiltExt = "1.2.0"
androidxHiltNavigationCompose = "1.2.0"
geckoviewExt="141.0.20250714153642"
lifecycleViewModel="2.9.2"
coroutinesExt="1.10.2"
browserExt="1.8.0"
webkitExt="1.14.0"
recyclerviewExt="1.4.0"
recyclerviewSelectionExt="1.2.0"
splashScreen="1.0.1"
roleManagerCompat="1.1.0"
coreAnimation="1.0.0"
corePerformance="1.0.0"
coreRemoteViews="1.1.0"
dynamicanimation="1.1.0"
navigationVer="1.0.0-alpha05"
cardview="1.0.0"
constraintlayout="1.1.1"
coordinatorlayout="1.3.0"
fragment="1.8.8"
viewpager="1.1.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-tv-foundation = { group = "androidx.tv", name = "tv-foundation", version.ref = "tvFoundation" }
androidx-tv-material = { group = "androidx.tv", name = "tv-material", version.ref = "tvMaterial" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycleViewModel" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidxHiltNavigationCompose" }
#hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt" }
#hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
#hilt-core = { group = "com.google.dagger", name = "hilt-core", version.ref = "hilt" }
#hilt-ext-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hiltExt" }
#hilt-ext-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "hiltExt" }
geckoview = { group = "org.mozilla.geckoview", name = "geckoview", version.ref = "geckoviewExt" }
androidx-compose-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "splashScreen" }
androidx-compose-core-role = { group = "androidx.core", name = "core-role", version.ref = "roleManagerCompat" }
androidx-compose-core-animation = { group = "androidx.core", name = "core-animation", version.ref = "coreAnimation" }
androidx-compose-core-animation-testing = { group = "androidx.core", name = "core-animation-testing", version.ref = "coreAnimation" }
androidx-compose-core-performance = { group = "androidx.core", name = "core-performance", version.ref = "corePerformance" }
androidx-compose-core-remoteviews = { group = "androidx.core", name = "core-remoteviews", version.ref = "coreRemoteViews" }
androidx-browser = { group = "androidx.browser", name = "browser", version.ref = "browserExt" }
androidx-webkit = { group = "androidx.webkit", name = "webkit", version.ref = "webkitExt" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerviewExt" }
androidx-dynamicanimation-ktx = { group = "androidx.dynamicanimation", name = "dynamicanimation-ktx", version.ref = "dynamicanimation" }
# For control over item selection of both touch and mouse driven selection
androidx-recyclerview-selection = { group = "androidx.recyclerview", name = "recyclerview-selection", version.ref = "recyclerviewSelectionExt" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-kotlinx-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutinesExt" }
androidx-cardview = { group = "androidx.cardview", name = "cardview", version.ref = "cardview" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "constraintlayout" }
androidx-coordinatorlayout = { group = "androidx.coordinatorlayout", name = "coordinatorlayout", version.ref = "coordinatorlayout" }
androidx-compose-fragment = { group = "androidx.fragment", name = "fragment-compose", version.ref = "fragment" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragment" }
androidx-fragment-testing = { group = "androidx.fragment", name = "fragment-testing", version.ref = "fragment" }
androidx-navigation-runtime = { group = "androidx.navigation3", name = "navigation3-runtime", version.ref = "navigationVer" }
androidx-navigation-ui = { group = "androidx.navigation3", name = "navigation3-ui", version.ref = "navigationVer" }
androidx-viewpager2 = { group = "androidx.viewpager2", name = "viewpager2", version.ref = "viewpager" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
